 version: 2
 jobs:
   oneBuild:
     docker:
       - image: circleci/node:7.1.0
     steps:
       - checkout
       - run: echo "A first hello"
   twoBuild:
     docker:
       - image: circleci/node:7.1.0
     steps:
       - checkout
       - run: echo "A first hello"
   workflows:
    version: 2
    oneBuild_and_twoBuild:
     jobs:
       - oneBuild
       - twoBuild