# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# CircleCIではnpm -gでのコマンド実行が出来ないため、
# 事前にfirebase-toolsをローカルでプロジェクトにインストールしておくようにしています。。
# yarn add --dev firebase-tools
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --no-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: 'gatsby build'
          command: yarn build
      - run:
          name: 'Deploy to firebase Hosting'
          command: cd functions && yarn install --no-lockfile && ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN #firebaseTokenはcircleciの環境変数

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master # masterブランチのみを実行対象